### ISSUE TITLE
export {default as v} from "mod";

### ISSUE THREAD

**Issue by sstur** [leebyron/ecmascript-more-export-from#10]
It might be worth mentioning that the following are synonymous:

```
import v from "mod";
import {default as v} from "mod";
```

likewise, your proposed:

```
export v from "mod";
```

... has an existing form:

```
export {default as v} from "mod";
```

This is not to invalidate your argument for parity between import from and export from. Just something worth mentioning for completeness.

**Comment by leebyron** [comment]
Great suggestion, will do!

**Comment by leebyron** [comment]
https://github.com/leebyron/ecmascript-export-default-from/commit/172623e0b034c616ff197f980af2eef462a60170
