### ISSUE TITLE
Take away from TC39 2015-5

### ISSUE THREAD

**Issue by leebyron** [leebyron/ecmascript-more-export-from#4]
Consensus on `export * as ns from "mod"` and `export default from "mod"` as clear and useful - both should go to Stage 2. There is still concern about confusion on `export v from "mod"` - should stay at Stage 1.
- [x] Split into three micro-proposals:
  - [x] export \* as ns from "mod"
  - [x] export default from "mod"
  - [x] export v from "mod"

**Comment by caridy** [comment]
great, thanks for the update @leebyron.

**Comment by leebyron** [comment]
4258790a34a400738625511a246b42a2e63ebe62

https://github.com/leebyron/ecmascript-export-ns-from

https://github.com/leebyron/ecmascript-export-default-from
