### ISSUE TITLE
question on export * as ns from 'm'

### ISSUE THREAD

**Issue by guybedford** [leebyron/ecmascript-more-export-from#5]
Will this export \* also skip exporting the default export?

**Comment by guybedford** [comment]
Actually I'd assume not as it is acting at the namespace level, instead of the exports level, which would make complete sense from the perspective of collisions.

**Comment by caridy** [comment]
Hmm, I'm not sure I understand the last statement @guybedford, but this has nothing to do with the default export, it just adds a new named export called `ns` that points to the exotic object that represents `m`, which is the same you will get when doing `import * as ns from "m"`, and that exotic object can have a `default` if `m` happens to have a default export.

Essentially, there is no possible collision with the `export * as ns...` form.

**Comment by guybedford** [comment]
@caridy thanks for the response - I thought it was analogous to `export *` (which skips the default export), but yes it is analogous to `import *` rather here.

**Comment by caridy** [comment]
> `export *` (which skips the default export)

where is this coming from? jejeje. as far as I can tell, `export * from` algo will only prevent re-exporting a named export if there is a collision with another `export` statement (by the order of definition), and keeping in mind that the default export is just a named export called `default`, there is really not distintion AFAIK.

**Comment by guybedford** [comment]
@caridy it is in the spec - 6c in https://people.mozilla.org/~jorendorff/es6-draft.html#sec-resolveexport.
