### ISSUE TITLE
Clarify Babel extension.

### ISSUE THREAD

**Issue by adriancooney** [leebyron/ecmascript-more-export-from#8]
Just in case anyone had the same issue looking for the babel "es7.exportExtensions" babel option, you can find it [here](http://babeljs.io/docs/plugins/transform-export-extensions/). Babel has exploded into loads of tiny little modules which you now have to install manually. To enable this, you need to install the `babel-plugin-transform-export-extensions` and add `transform-export-extensions` to your `plugins` in your config.

Could be worth updating the README.md.

**Comment by leebyron** [comment]
Thanks, updated the micro-proposals:

https://github.com/leebyron/ecmascript-export-ns-from
https://github.com/leebyron/ecmascript-export-default-from
