### ISSUE TITLE
Symmetry between import and export

### ISSUE THREAD

**Issue by Download** [leebyron/ecmascript-more-export-from#9]
> Symmetry between import and export
> ...
> export {v} from "mod";
> Is symmetric to:
> 
> import {v} from "mod";
> However, where importing v introduces a name in the local scope, export-from v does not alter the local scope, instead creating an export entry.

I don't get this. All my instincts tell me that 

``` js
export {v} from 'mod';
```

should be equivalent to doing

``` js
import {v} from 'mod';
export v;
```

But I have indeed noted (via Babel) that indeed, when I do 

``` js
export {v} from 'mod';
```

I can't actually use `v` later on in that code:

``` js
v.whatever();  // Uncaught TypeError: Cannot read property 'whatever' of undefined(…)
```

What is the rationale behind this? I am struggling with this on a regular basis. I then try to do this instead:

``` js
import {v} from 'mod';
export v;
```

And it complains about 'Unexpected token' on the export statement. I have _many_, _many_ commits in my Git repo with all kinds of small permutations on export statements to get rid of issues that keep creeping up. 

Similarly, for some reason, this breaks with 'Unexpected token':

``` js
export {x, y} from 'mod';
```

I have to change it to 

``` js
export {x} from 'mod';
export {y} from 'mod';
```

Now these could be Babel issues, but I just wanted to give you this feedback from using it in practice.

I would personally expect 

``` js
export {v} from 'mod';
```

to be equavalent to

``` js
import {v} from 'mod';
export v;
```

...so for `v` to be defined after this has run. `v` being undefined is unexpected for me and I wonder what it's application would be?

I would also suggest (but probably that ship has already sailed) that `import` and `export` would give interop with CJS `require` more priority. Until recently I could do this:

_module a.js_

``` js
export default function a();
```

_module b.js_

``` js
var a = require('./a');
```

Now, since recently, I have to do this:

_module b.js_

``` js
var a = require('./a').default;
```

According to the Babel people this was changed due to a spec change? If so I think that change is one for the worse...

Anyway... don't want to be whining. All in all I love imports and the `export from` syntax and I'll probably get used to whatever it turns out to be. Keep up the great work!

**Comment by ericf** [comment]
The export-from syntax does not create a local binding, making it different importing and re-exporting. A primary use-case for export-from is to define a top-level package module for a library. [Here's an example](https://github.com/yahoo/react-intl/blob/master/src/react-intl.js), this happens to also `import` and re-`export` a function because the package module is also calling a function it's re-exporting.

As for the change in Babel 6 for how ES modules are compiled to CJS, this is to support the live bindings and circular dependencies features of ES modules. When Babel compiles a ES module that uses export-from to a CJS `require()` it will do so using `Object.defineProperty` to create getters which reference the value from the binding that's being re-exported. This means that the default export has to be a property on an object in order for Babel to generate a getter, e.g.

**a.js**

``` js
export default 42;
```

**b.js**

``` js
export {default} from './a.js';
```

Babel 6 will compile b.js to this CJS code:

``` js
var a = require('./a');

Object.defineProperty(exports, 'default', {
  enumerable: true,
  get: function get() {
    return a['default'];
  }
});
```

**Comment by Download** [comment]
ok I kinda understand that. It's definitely a good reason I hadn't considered :+1: 

But still I wonder, why not make the variable available in the local scope as well?

**Comment by leebyron** [comment]
Thanks for the comment. I added more detail when refactoring into micro-proposals:
https://github.com/leebyron/ecmascript-export-ns-from

To address some of your questions, I believe many of these are small typing mistakes or perhaps babel issues:

For example:

> ``` js
> import {v} from 'mod';
> export v;
> ```

Should be:

``` js
import {v} from 'mod';
export {v};
```

To parse correctly. This will both import `v` into the local scope as well as include it in this module's exports.

And this case is totally valid, perhaps there was a parser bug?

``` js
export {x, y} from 'mod';
```

**Comment by leebyron** [comment]
> But still I wonder, why not make the variable available in the local scope as well?

The purpose of the "export from" forms is to explicitly not alter the local scope while creating "package" modules.

This proposal doesn't suggest altering the behavior of any of the existing "export from" forms, just adding additional cases that previously weren't considered.

**Comment by Download** [comment]
@leebyron Thanks for your explanations. I still have one question:

> For example:
> 
> ``` js
> import {v} from 'mod';
> export v;
> ```
> 
> Should be:
> 
> ``` js
> import {v} from 'mod';
> export {v};
> ```

I don't get this. Why is this different from:

``` js
const v = 'whatever';
export v;
```

Why do we need to enclose `v` in curly braces?

**Comment by leebyron** [comment]
That is because `export v;` is not valid syntax while `export {v}` is valid syntax. As I understand it, that original decision was made for two reasons: to mirror the `import { v } from "mod"` and to remove any ambiguity from other `export ___` syntax forms.

You can read more about the existing syntax at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export or in the spec at https://tc39.github.io/ecma262/#prod-ExportDeclaration

**Comment by Download** [comment]
Wow, you are fast! :+1: 

I am currently doing things like this in my code

``` js
export const store = createStore(
    createReducer(app),
    typeof window == 'object' && window.__data && fromJSON(window.__data) || undefined,
    storeEnhancer
);
```

(from a React / Redux app)

also, I'm doing this:

``` js
export const routes = (
    <Route path="/" component={App}>
        // ....
    </Route>
);
```

(react router config)

It works great with Babel. Is it wrong?
If not, then why would there be a difference between

``` js
export const x = 10;
```

and

``` js
const x = 10;
export x;
```

This is very confusing to me...

_delves into docs_

**Comment by Download** [comment]
Mmm it seems the `const` sorta triggers a different path in the syntax. I guess I'm looking at `export` too much as if it was just a function. At least with this info I can explain some of those `Unexpected token` issues I've been having. Thanks very much for your helpful comments!

**Comment by leebyron** [comment]
There's nothing wrong with what you're doing.

There are two primary forms of `export`: exporting a previously defined variable (`export ExportClause`) and exporting a definition as you define it (`export VariableStatement` and `export Declaration`). You can see them defined in https://tc39.github.io/ecma262/#prod-ExportDeclaration

You use exporting a definition as you define it by prefixing `export` to the definition:

``` js
export const x = 10;
export function doSomething() {};
export class MyClass {};
```

You can export previously defined variables with the _ExportClause_ form:

``` js
export { x };
export { doSomething, MyClass };
```

**Comment by Download** [comment]
@leebyron Yes it's much more clear to me now. I was using a wrong mental model of `export`.
